food_income_types:
  - standard_name: "代理商E配送收入"
    service_package: "代理商E配送"
  - standard_name: "城代拼团收入"
    service_package: "城代拼团"
  - standard_name: "城代选推收入"
    service_package: "城代选推"
  - standard_name: "代理商E基础KA收入"
    service_package: "代理商E基础KA"
  - standard_name: "城代拼团到店自取收入"
    service_package: "城代拼团到店自取"
  - standard_name: "城代到店自取收入"
    service_package: "城代到店自取"
  - standard_name: "代理商E基础收入"
    service_package: "代理商E基础"

retail_income_types:
  - standard_name: "代理商新零售超客配收入"
    service_package: "代理商新零售超客配"
  - standard_name: "代理商e配送KA收入"
    service_package: "代理商e配送KA"
  - standard_name: "城代e配送收入"
    service_package: "城代e配送"
  - standard_name: "拼团收入"
    service_package: "拼团-代零单拼、拼团-代零多拼"
  - standard_name: "代理商e基础收入"
    service_package: "代理商e基础"
  - standard_name: "代理商e基础KA收入"
    service_package: "代理商e基础KA"
  - standard_name: "代理商新零售超客配KA收入"
    service_package: "代理商新零售超客配KA"
  - standard_name: "城代到店自取KA收入"
    service_package: "城代到店自取KA"

income_amount_field: "settlement_amount"
order_dedup_field: "order_id"
